<?php

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function workflow_hide_fields_help($path, $arg) {
  switch ($path) {
    case "admin/help#workflow_hide_fields":
      // TODO: Improve help
      return '<p>' . t("Hide given fields in specific states.") . '</p>';
      break;
  }
}

/**
 * Implements hook_menu().
 */
function workflow_hide_fields_menu() {
  $items = array();
  $items['admin/config/content/workflow_hide_fields'] = array(
    'title' => 'Workflow hide fields',
    'description' => 'Configuration for Workflow hide fields',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('workflow_hide_fields_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Page callback: Hide fields settings
 *
 * @see workflow_hide_fields_menu()
 */
function workflow_hide_fields_form($form, &$form_state) {

  //TODO: This is just... dummy, do something functional
  $form['workflow_hide_fields_thefields'] = array(
    '#type' => 'textfield',
    '#title' => t('Fields to be hidden'),
    '#default_value' => variable_get('workflow_hide_fields_thefields', ""),
    '#description' => t("List of fields to be hidden.")
  );

  return system_settings_form($form);
}

/**
 * Implements hook_field_access
 */
function workflow_hide_fields_field_access($op, $field, $entity_type, $entity, $account) {
  // If the entity is equal as the given type
  if (isset($entity->type) && $entity->type == "orden_de_trabajo") { // TODO: Convert to variable "orden_de_trabajo"
  
    // If the field is the right one
    if (($field['field_name'] == 'field_responsable') && ($op == 'edit')) { // TODO: Convert to variable 'field_responsable'
      $propiedad = 'field_flujo_de_trabajo'; // TODO: Convert to variable 'field_flujo_de_trabajo'
      $en_creacion = !isset($entity->$propiedad);
      
      $state = '0';
      if (!$en_creacion) {
        $entity_property = $entity->$propiedad;
        $lang = $entity_property['#language'];
        $state = $entity_property[$lang][0]['value'];
      }

      if ($en_creacion || $state != '2')
        return user_access('administer nodes', $account);
    }
    
    // If the field is the right one
    if (($field['field_name'] == 'field_calificacion') && ($op == 'edit')) { // TODO: Convert to variable "field_calificacion"
      $propiedad = 'field_flujo_de_trabajo'; // TODO: Convert to variable 'field_flujo_de_trabajo'
      $en_creacion = !isset($entity->$propiedad);
      
      $state = '0';
      if (!$en_creacion) {
        $entity_property = $entity->$propiedad;
        $lang = $entity_property['#language'];
        $state = $entity_property[$lang][0]['value'];
      }

      if ($en_creacion || $state != '6')
        return user_access('administer nodes', $account);
    }
    
    
    return TRUE;
  }
}

function workflow_hide_fields_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'orden_de_trabajo_node_form') { // TODO: Convert to variable 'orden_de_trabajo_node_form'
    unset($form['actions']['preview']);
    $node = $form_state['node'];
    $new_node = (!isset($node->nid) || isset($node->is_new));

    if (!$new_node) {
      $form['title']['#disabled'] = TRUE; // TODO: Convert to variable 'title'
      $form['body']['#disabled'] = TRUE; // TODO: Convert to variable 'body'
    }
  }
}

function workflow_hide_fields_node_access($node, $op, $account) {
  // Add your extra validation checks here
  // To deny access return NODE_ACCESS_DENY otherwise return nothing or NODE_ACCESS_IGNORE.

  if (isset($node->type) && $node->type == "orden_de_trabajo") { // TODO: Convert to variable "orden_de_trabajo"
    global $user;

    $logueado = $user->uid;
    $autor = $node->uid;

    $usuario_logueado_es_supervisor = false;

    if (in_array('supervisor', $user->roles)) { // TODO: Convert to variable 'supervisor'
      $usuario_logueado_es_supervisor = true; // TODO: Change the variable name
    }

    $property = 'field_flujo_de_trabajo'; // TODO: Convert to variable 'field_flujo_de_trabajo'
    $node_property = $node->$property;
    $lang = $node_property['#language'];
    $estado = $node_property[$lang][0]['value'];
    
    $property_resp = 'field_responsable';
    $responsable = NULL;
    if (isset($node->$property_resp)) {
      $node_property_resp = $node->$property_resp;
      if (isset($node_property['#language']))
      {
        $lang = $node_property['#language'];
        if (isset($node_property_resp[$lang]))
          if (isset($node_property_resp[$lang][0]))
            $responsable = $node_property_resp[$lang][0]['target_id'];
      } 
    }

    if ($op == "update") {
      $en_validacion = $estado == 2;
      
      $final_states = array(6, 7);
      $terminado = in_array($estado, $final_states);
      //$terminado = ($estado == 6) || ($estado == 7);

      $supervisor_validando = $en_validacion && $usuario_logueado_es_supervisor;

      if ($supervisor_validando) {
        return NODE_ACCESS_IGNORE;
      }

      if (!$en_validacion && !$terminado) {
        if ($responsable == $logueado) {
          return NODE_ACCESS_IGNORE;
        }
      }

      if (($autor == $logueado) && $terminado) {
        return NODE_ACCESS_IGNORE;
      }
      else
        return NODE_ACCESS_DENY;
    }

    // If there is a responsible (state >= 3) and the logged in user is that responsible, he/she can see it
    $states_with_responsible = array(4, 5, 6, 7);
    if (in_array($estado, $states_with_responsible)) {
      if ($responsable == $logueado) {
        return NODE_ACCESS_IGNORE;
      }
    }

    // If only author and supervisor can see it
    if (($autor != $logueado) && (!$usuario_logueado_es_supervisor)) {
      return NODE_ACCESS_DENY;
    }
  }
}
